spring.application.name=API-Comercio

#Archivo: src/main/resources/application.properties

# Puerto del servidor web
server.port=8080

# Configuración de la conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/comercio_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA: automatiza la creación y actualización de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración JWT
# La firma secreta (debe ser larga y compleja)
jwt.secret=UnaClaveSuperSecretaParaNuestraApiComercioQueDebeSerLarga1234567890
# Tiempo de vida de la pulsera en milisegundos (86400000 = 1 día)
jwt.expiration=86400000